### ISSUE TITLE
Doesn't change songs when you skip or go back.

### ISSUE THREAD

**Issue by rads560** [JoeKarlsson/react-spotify-player#2]
Hi there, thanks for the wonderful tutorial! In my project it doesn't seem to update the web UI based on what's playing or not playing in real time. It only knows the song that was playing when you log in. Is that expected? How would I extend this to change the song as I change what's playing in my Spotify account? Thanks for your help!

**Comment by moodiest** [comment]
Also experiencing this issue, @JoeKarlsson

**Comment by JoeKarlsson** [comment]
Thank you for reporting the bug. Let me see if I can replicate it locally.

**Comment by JoeKarlsson** [comment]
In order to get this fixed, we will need to poll the API endpoint to get the most up to date currently playing information. I'm thinking every 5-10 seconds.

**Comment by JoeKarlsson** [comment]
If anyone is up for implementing this - I would gladly merge their PR. This is a good issue for first timers :)

**Comment by tomashodek** [comment]
For a quick fix, you can just add this line to the bottom of `getCurrentlyPlaying()` function.
```
setTimeout(() => this.getCurrentlyPlaying(token), 7500);
``` 
It will call the get function every 7,5s recursively.
