### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by llacy730** [JoeKarlsson/react-spotify-player#3]
I'm getting the following error:

 Line 14:7:  Parsing error: Identifier 'hash' has already been declared

  12 | ];
  13 | // Get the hash of the url
> 14 | const hash = window.location.hash
     |       ^
  15 |   .substring(1)
  16 |   .split("&")
  17 |   .reduce(function(initial, item) {

**Comment by 6alexspeakers9** [comment]
Hello,
I think you should just try to import hash differently, using this way :
replace `import hash from ./hash` y this : `import "../node_modules/hash.js";` 
If it doesn't work, search for the "hash.js" file in your project directory.

**Comment by JoeKarlsson** [comment]
This issue looks similar to issues #5. Closing this issue.
