### ISSUE TITLE
Player not working due to insecure "Samesite=None" cookies

### ISSUE THREAD

**Issue by Dusch4593** [JoeKarlsson/react-spotify-player#4]
After clicking "Login to Spotify", I was taken to a page that said something went wrong. Apparently, Chrome is intending on only delivering Samesite cookies that are set as "Secure". Is that why, upon looking in the "Network" section of Chrome's dev tools, I'm getting a 404 error? (see below)

<img width="1458" alt="spotify_error" src="https://user-images.githubusercontent.com/23144845/67108539-c1324480-f19c-11e9-884c-56016718b9ed.png">

**Comment by JoeKarlsson** [comment]
I'll see if I can replicate this issue in Chrome.

**Comment by JoeKarlsson** [comment]
I just tried this in Chrome and I was not able to replicate this error. Is anyone else able to replicate this error locally?

**Comment by brnhache** [comment]
I am getting the same 404. Being new to react I'm fumbling through this, but it looks like there is something fishy with the hash that feeds the token generator. 

importing hash from a local file (that we were supposed to create, presumably)
and then declaring const hash causes an error of its own. @Dusch4593 did you have this issue as well?

removing that import allows the code to compile.

I also noticed that window.location.hash seems to be an empty string while window.location holds data... must have something to do with this mystery "./hash" file?

**Comment by JoeKarlsson** [comment]
Couple of questions - Is this hash file in your project? Here it is in my code.

https://github.com/JoeKarlsson/react-spotify-player/blob/master/src/hash.js

Also - what's browser are you using?

**Comment by brnhache** [comment]
I removed the hash from app.js and am now importing from hash.js, still have the same problem though. I am using chrome.
![image](https://user-images.githubusercontent.com/40395957/74801093-8dc70a00-52a3-11ea-88e4-161d0b2db917.png)

thanks

**Comment by JoeKarlsson** [comment]
@brnhache - is your code on GitHub? I want to see if I can reproduce your error locally to help troubleshoot it. Relatedly, have you tried to just clone my repo? Does it have the same issue?

**Comment by brnhache** [comment]
@JoeKarlsson  just pushed it. https://github.com/brnhache/React-Projects

**Comment by JoeKarlsson** [comment]
@brnhache - looks like that repo is private...

**Comment by brnhache** [comment]
@JoeKarlsson sorry bud, im not very good at this yet. seems like it is public tho...i edited my comment, you may have gotten the url to the wrong repo. https://github.com/brnhache/react-spotify-app
it looks like its set to public by default : 
![image](https://user-images.githubusercontent.com/40395957/75049799-c845c800-5498-11ea-8074-68c82f58cb7b.png)

**Comment by JoeKarlsson** [comment]
There we go - that worked. Looks like it was a bad URL. I'll check it out.

**Comment by JoeKarlsson** [comment]
I am able to reproduce your issue using your codebase - def looks like a CORS issue. What happens when you clone my repo? do you still get the same issue? It still works on my repo, so I don't actually think this is a browser issue.

**Comment by MHeininger1** [comment]
It looks like the article is missing the "?" after "{authEndpoint}" for the login href in the article. @brnhache fix this in your repo and see if that fixes your problem.

**Comment by brnhache** [comment]
I had that already. thanks for the suggestion. after following another
short tutorial it seems like my callback function was not set properly.

cheers
