### ISSUE TITLE
Can't resolve

### ISSUE THREAD

**Issue by dennischrist** [JoeKarlsson/react-spotify-player#6]
Hi,

I get the following error:

Failed to compile.

./src/App.js
Module not found: Can't resolve './config' in '/Users/xxxxxxx/Desktop/player/src'

Any suggestions for what I should do?

I'm a super newbie thanks!

**Comment by JoeKarlsson** [comment]
great question! I will update the documentation so it's more clear what you need to do to get the project setup. 

But for you, you need to change `/src/config_example.js` to `/src/config.js`. This is common syntax for OSS so the project doesn't accidentally expose any private API data. Hope that helps!

**Comment by JoeKarlsson** [comment]
@TODO - Update the documentation to make project setup more clear.

**Comment by JoeKarlsson** [comment]
Alright - I updated the README.md with instructions for how to resolve this error. Closing this ticket. Create a new issue if you still are having trouble getting this working.
